### ISSUE TITLE
live view isn't optional

### ISSUE THREAD

**Issue by plural** [kylemcdonald/ofxEdsdk#37]
I like the wrapper around the SDK, but I don't always want to have live view enabled.  It would be nice to be able to easily turn live view on and off easily.

I have a (crappy) patch in progress for this that I'll try to tidy up and get out for review shortly.

**Comment by kylemcdonald** [comment]
this is available in the develop branch https://github.com/kylemcdonald/ofxEdsdk/blob/develop/src/ofxEdsdk.h#L19

but i'm waiting until 0.9.0 is released to merge.

**Comment by plural** [comment]
awesome! Thanks.
